name: Deploy with Copilot

on:
  push:
    branches:
      - main  # Trigger only on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # or use: ${{ secrets.AWS_REGION }}

    - name: Install AWS Copilot CLI
      run: |
        curl -Lo copilot-cli https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
        chmod +x copilot-cli
        sudo mv copilot-cli /usr/local/bin/copilot

    - name: Build Backend Docker image
      run: |
        docker build -t backend-test -f Backend-Dockerfile .

    - name: Build Frontend Docker image
      run: |
        docker build -t frontend-test -f ppp-frontend/Frontend-Dockerfile ./ppp-frontend

    - name: Deploy Frontend
      run: |
        copilot deploy --name frontend --env prod

    - name: Deploy Backend
      run: |
        copilot deploy --name backend --env prod
