name: Deploy with Copilot

on:
  push:
    branches:
      - main  # Trigger only on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_REGION: ${{ secrets.AWS_REGION }}
      ECR_ACCOUNT_ID: ${{ secrets.ECR_ACCOUNT_ID }}
      FRONTEND_REPO: ppp-data-tool/frontend
      BACKEND_REPO: ppp-data-tool/backend
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # or use: ${{ secrets.AWS_REGION }}

    - name: Install AWS Copilot CLI
      run: |
        curl -Lo copilot-cli https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
        chmod +x copilot-cli
        sudo mv copilot-cli /usr/local/bin/copilot

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $ECR_REGION | \
          docker login --username AWS --password-stdin $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com

    - name: Build and Push Frontend Image
      run: |
        docker build -t $FRONTEND_REPO:latest -f ppp-frontend/Frontend-Dockerfile ppp-frontend
        docker tag $FRONTEND_REPO:latest $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/$FRONTEND_REPO:latest
        docker push $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/$FRONTEND_REPO:latest

    - name: Build and Push Backend Image
      run: |
        docker build -t $BACKEND_REPO:latest -f Backend-Dockerfile ppp-backend
        docker tag $BACKEND_REPO:latest $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/$BACKEND_REPO:latest
        docker push $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/$BACKEND_REPO:latest

    - name: Deploy Frontend
      run: |
        copilot deploy --name frontend --env prod

    - name: Deploy Backend
      run: |
        copilot deploy --name backend --env prod
